export const piSubagentExtension = `// Generated by agents-cli. Regenerate instead of editing this file.
// This lightweight project extension delegates one task to an isolated Pi process.
import { spawn } from "node:child_process";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { Type } from "@earendil-works/pi-ai";
import { defineTool, type ExtensionAPI } from "@earendil-works/pi-coding-agent";

type Agent = { name: string; description: string; tools?: string[]; prompt: string };

function parseAgent(file: string): Agent | undefined {
  const source = fs.readFileSync(file, "utf8");
  const match = source.match(/^---\\n([\\s\\S]*?)\\n---\\n([\\s\\S]*)$/);
  if (!match) return undefined;
  const name = match[1].match(/^name:\\s*(.+)$/m)?.[1]?.trim();
  const description = match[1].match(/^description:\\s*(.+)$/m)?.[1]?.trim().replace(/^"|"$/g, "");
  const tools = match[1].match(/^tools:\\s*(.+)$/m)?.[1]?.split(",").map((item) => item.trim()).filter(Boolean);
  if (!name || !description) return undefined;
  return { name, description, tools, prompt: match[2].trim() };
}

function discover(cwd: string): Agent[] {
  let current = cwd;
  while (true) {
    const directory = path.join(current, ".pi", "agents");
    if (fs.existsSync(directory)) {
      return fs.readdirSync(directory)
        .filter((name) => name.endsWith(".md"))
        .map((name) => parseAgent(path.join(directory, name)))
        .filter((agent): agent is Agent => Boolean(agent));
    }
    const parent = path.dirname(current);
    if (parent === current) return [];
    current = parent;
  }
}

function invocation(args: string[]): { command: string; args: string[] } {
  const script = process.argv[1];
  if (script && !script.startsWith("/$bunfs/root/") && fs.existsSync(script)) {
    return { command: process.execPath, args: [script, ...args] };
  }
  const executable = path.basename(process.execPath).toLowerCase();
  return /^(node|bun)(\\.exe)?$/.test(executable)
    ? { command: "pi", args }
    : { command: process.execPath, args };
}

const tool = defineTool({
  name: "subagent",
  label: "Subagent",
  description: "Delegate one task to an isolated project role from .pi/agents. Use this for specialist implementation, review, QA, or orchestration work.",
  parameters: Type.Object({
    agent: Type.String({ description: "Agent name from .pi/agents" }),
    task: Type.String({ description: "Complete task, scope, constraints, and expected evidence" }),
  }),
  async execute(_id, params, signal, _onUpdate, ctx) {
    const agents = discover(ctx.cwd);
    const agent = agents.find((candidate) => candidate.name === params.agent);
    if (!agent) {
      const available = agents.map(({ name }) => name).join(", ") || "none";
      throw new Error(\`Unknown project agent '\${params.agent}'. Available: \${available}.\`);
    }

    const tempDirectory = fs.mkdtempSync(path.join(os.tmpdir(), "agents-cli-pi-"));
    const promptFile = path.join(tempDirectory, "system.md");
    fs.writeFileSync(promptFile, agent.prompt, { encoding: "utf8", mode: 0o600 });
    const args = ["--print", "--no-session", "--no-extensions", "--append-system-prompt", promptFile];
    if (ctx.model) args.push("--model", \`\${ctx.model.provider}/\${ctx.model.id}\`);
    if (ctx.thinkingLevel) args.push("--thinking", ctx.thinkingLevel);
    if (agent.tools?.length) args.push("--tools", agent.tools.join(","));
    args.push("--", \`Task: \${params.task}\`);
    const command = invocation(args);

    try {
      const output = await new Promise<string>((resolve, reject) => {
        const child = spawn(command.command, command.args, { cwd: ctx.cwd, shell: false, stdio: ["ignore", "pipe", "pipe"] });
        let stdout = "";
        let stderr = "";
        child.stdout.on("data", (chunk) => { stdout += chunk.toString(); });
        child.stderr.on("data", (chunk) => { stderr += chunk.toString(); });
        child.on("error", reject);
        child.on("close", (code) => code === 0 ? resolve(stdout.trim()) : reject(new Error(stderr.trim() || \`Pi subagent exited with code \${code}.\`)));
        const abort = () => child.kill("SIGTERM");
        if (signal.aborted) abort();
        else signal.addEventListener("abort", abort, { once: true });
      });
      return { content: [{ type: "text", text: output || "Subagent completed without text output." }], details: { agent: agent.name } };
    } finally {
      fs.rmSync(tempDirectory, { recursive: true, force: true });
    }
  },
});

export default function (pi: ExtensionAPI) {
  pi.registerTool(tool);
}
`;
