import { readFile, readdir } from "node:fs/promises";
import { basename, join } from "node:path";
import type { InstallFile } from "../../install/engine.js";

export interface CodexRenderOptions {
  catalogRoot: string;
  selectedSkills?: string[];
}

interface AgentSource {
  id: string;
  description: string;
  permission: Record<string, unknown>;
  body: string;
}

export async function renderCodex(options: CodexRenderOptions): Promise<InstallFile[]> {
  const agentRoot = join(options.catalogRoot, "agents");
  const paths = (await readdir(agentRoot)).filter((path) => path.endsWith(".md")).sort();
  const skills = options.selectedSkills ?? [];
  const agents = await Promise.all(paths.map(async (path) => parseAgent(path, await readFile(join(agentRoot, path), "utf8"))));
  const files = agents.map((agent) => ({
    path: `.codex/agents/${agent.id}.toml`,
    content: renderAgent(agent, skills),
  }));
  files.push({
    path: ".codex/AGENTS.md",
    content: renderInstructions(agents.length, skills),
  });
  files.push({
    path: ".codex/agents/manifest.json",
    content: `${JSON.stringify({ schemaVersion: 1, platform: "codex", agents: agents.map(({ id }) => id), skills }, null, 2)}\n`,
  });
  return files;
}

async function parseAgent(path: string, source: string): Promise<AgentSource> {
  const sections = source.split("---");
  if (sections.length < 3) throw new Error(`Agent is missing front matter: ${path}`);
  const frontMatter = sections[1];
  const description = frontMatter.match(/description:\s*["']([^"']+)["']/)?.[1];
  const permissionText = frontMatter.match(/permission:\s*(\{.*\})/s)?.[1];
  if (!description || !permissionText) throw new Error(`Agent front matter is incomplete: ${path}`);
  return {
    id: basename(path, ".md"),
    description,
    permission: JSON.parse(permissionText) as Record<string, unknown>,
    body: sections.slice(2).join("---").trim(),
  };
}

function renderAgent(agent: AgentSource, skills: string[]): string {
  const permission = agent.permission;
  const edit = permission.edit as string | Record<string, unknown> | undefined;
  const task = permission.task as string | Record<string, unknown> | undefined;
  const instructions = [
    agent.body,
    "",
    "## Codex adapter contract",
    "",
    "This named role is rendered for Codex. Codex sandbox and approval settings, plus parent-session permissions, remain authoritative.",
    `\nSkill references (installed by the platform installer):${skills.length ? `\n${skills.map((skill) => `- .codex/skills/${skill}/SKILL.md`).join("\n")}` : " none selected."}`,
    "\nOriginal runtime permission metadata (informational):",
    JSON.stringify(permission, null, 2),
  ].join("\n");
  const lines = [
    "# Generated by agents-cli; edit the catalog source instead.",
    `name = ${JSON.stringify(agent.id)}`,
    `description = ${JSON.stringify(agent.description)}`,
  ];
  if (edit === "deny") lines.push('sandbox_mode = "read-only"');
  lines.push(`developer_instructions = ${JSON.stringify(instructions)}`);
  if (task === "deny") lines.push("", "[agents]", "enabled = false");
  return `${lines.join("\n")}\n`;
}

function renderInstructions(agentCount: number, skills: string[]): string {
  return `# Codex project instructions\n\nThis project was initialized with agents-cli. The Codex adapter rendered ${agentCount} named agent roles under ".codex/agents/".\n\nSelected skills are installed under ".codex/skills/" by the platform installer${skills.length ? `: ${skills.join(", ")}` : "; none selected"}.\n\nGenerated role files are derived from the repository catalog. Do not add credentials or absolute paths to generated configuration. Runtime sandbox and approval settings remain authoritative over textual instructions.\n`;
}
